// Auto-generated by the i18n Regolith filter. Do not edit — regenerated every build.
declare module '@bedrock-core/generated/i18n' {
	type Own = typeof import('./en_US').default;
	type Lib_core = typeof import('@bedrock-core/config/i18n/en_US').default & typeof import('@bedrock-core/guides/i18n/en_US').default;

	const bundle: {
		readonly namespace: string;
		readonly defaultLocale: 'en_US';
		readonly libs: readonly ['core'];
		/** locale → flat path → template ({{var}} form; vanilla entries only where referenced) */
		readonly locales: Record<string, Record<string, string>>;
		/** flat path → interpolation argument order (default locale appearance order) */
		readonly args: Record<string, readonly string[]>;
		/** locale → REAL key → value: .lang passthrough (guides, hand-written) for measurement */
		readonly extra: Record<string, Record<string, string>>;
		/** Type-only: the tree the t()/key()/raw() selectors navigate. Absent at runtime. */
		readonly resources?: Omit<Own, 'core' | 'vanilla'> & {
			readonly core: Lib_core;
			readonly vanilla: import('@bedrock-core/generated/i18n-vanilla').VanillaResources;
		};
	};
	export default bundle;
}
