// Ambient declaration for the itemAuxMap generated by the item-aux Regolith filter.
// The actual JSON file (itemAuxMap.generated.json) is gitignored and only exists after
// Regolith runs. This declaration lets TypeScript type-check imports before that.
declare module '*/itemAuxMap.generated.json' {
  const value: Record<string, number>;

  export default value;
}
