approvedGitRepositories: []

enableGlobalCache: true

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmScopes:
  bedrock-core:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN}"
    npmRegistryServer: "https://registry.npmjs.org"
