// GENERATED by the ui-compile filter — do not edit.
//
// Compiled from the screen of the same name. Every number below is an
// allocation the compiler made; address slots by name and they stay correct
// when the layout moves.

/** Slot names this screen draws, in the order it draws them. */
export type SlotName = 'toggle' | 'bay_0' | 'bay_1' | 'bay_2' | 'bay_3' | 'bay_4' | 'bay_5' | 'bay_6' | 'bay_7';

/** Channel names this screen reads. */
export type ChannelName = 'charge';

/** Container index of each drawn slot. */
export const slots = {
  toggle: 1,
  bay_0: 2,
  bay_1: 3,
  bay_2: 4,
  bay_3: 5,
  bay_4: 6,
  bay_5: 7,
  bay_6: 8,
  bay_7: 9,
} as const satisfies Record<SlotName, number>;

/** Container index of each bank slot backing a channel. */
export const channels = {
  charge: 10,
} as const satisfies Record<ChannelName, number>;

export const screen = {
  /** JSON UI namespace the layout was emitted into. */
  namespace: 'bcui_demo',
  /** Written into the sentinel's durability so the router can pick this layout. */
  layoutId: 1,
  /** Carries the routing keys. Never drawn. */
  sentinelSlot: 0,
  /** Slots the layout draws: `1 .. drawn`. */
  drawn: 9,
  /** Bank slots backing channels, immediately after the drawn range. */
  channelCount: 1,
  /** What `minecraft:inventory` on the host entity must be sized to. */
  inventorySize: 11,
  /** Entity the screen was attached to, if the source named one. */
  entity: undefined,
} as const;
