// GENERATED by the ui-compile filter — do not edit.
//
// Compiled from the screen of the same name. Every number below is an
// allocation the compiler made, and every list is in the order the screen
// declares them — which is the order the runtime re-renders them in.

import Screen from './demo.screen';

/**
 * Where each drawn slot is, and what the player may do with it.
 *
 * In document order, matching the order slots appear in the component. The role
 * belongs to the SCREEN rather than to a script: a furnace's output slot is an
 * output slot whatever is attached to it. The runtime enforces it a tick after
 * the fact, because a container gives no way to veto a move.
 */
export const slots = [
  { slot: 1, role: 'button' },
  { slot: 2, role: 'button' },
  { slot: 3, role: 'button' },
  { slot: 4, role: 'button' },
  { slot: 5, role: 'input' },
  { slot: 6, role: 'output' },
  { slot: 7, role: 'both' },
] as const;

/**
 * Where each channel lives and how wide it is, in document order.
 *
 * A `text` channel spans one container slot per character: the code rides that
 * slot's stack size, which is the only value writable in place, and the layout
 * localizes it back into a glyph.
 */
export const channels = [
  { slot: 8, carrier: 'text', length: 8 },
  { slot: 16, carrier: 'text', length: 26 },
  { slot: 42, carrier: 'ratio', length: 1 },
  { slot: 43, carrier: 'text', length: 6 },
  { slot: 49, carrier: 'text', length: 10 },
  { slot: 59, carrier: 'text', length: 16 },
] as const;

export const screen = {
  /** JSON UI namespace the layout was emitted into. */
  namespace: 'bcui_demo',
  /** Written into the sentinel's durability so the router can pick this layout. */
  layoutId: 1,
  /** Carries the routing keys. Never drawn. */
  sentinelSlot: 0,
  /** Slots the layout draws: `1 .. drawn`. */
  drawn: 7,
  /** Bank slots backing channels, immediately after the drawn range. */
  channelCount: 67,
  /** What `minecraft:inventory` on the host entity must be sized to. */
  inventorySize: 75,
  /** Entity the screen was attached to, if the source named one. */
  entity: 'core:spike_container',
} as const;

/** The component itself, re-rendered per player to produce the live values. */
export { Screen };
