// GENERATED by the ui-compile filter — do not edit.
//
// Every compiled screen, re-exported under its own name. Import the handle
// and hand it to `createContainerScreen`; it carries the slot indices, the
// bank layout and the routing key the compiler chose.

export * as demo from './demo';
