// GENERATED by the ui-compiler filter — do not edit.
//
// The screens this addon compiled, as the keys they are navigated by. Declared
// so the editor can offer them: `navigate()` and `<Link to>` take one of these,
// and still accept another addon's key — a screen this build never saw is
// resolved at runtime from the reference its owner published.

declare module '@bedrock-core/ui-runtime' {
  interface ScreenKeys {
    "core:guide_commands": true;
    "core:guide_getting_started_first_screen": true;
    "core:guide_getting_started_installation": true;
    "core:guide_home": true;
    "core:guide_home_back": true;
    "core:guide_intro": true;
    "core:framework": true;
  }
}

export {};
