import { createContext } from '../core/fabric/context';

export interface ItemAuxData {
  /** Raw numeric IDs for all vanilla items/blocks (typeId → raw_id). */
  vanillaRawIds: Record<string, number>;
  /** Offset added to |minVanillaRawId| to compute the custom block base ID. */
  blockBaseOffset: number;
  /**
   * First vanilla raw_id that may be displaced by developer-build items absent
   * from the public API. At runtime, any extra `minecraft:` items found via
   * `ItemTypes.getAll()` that are not in `vanillaRawIds` are counted, and that
   * count is added to the offset for all vanilla items with raw_id >= this value.
   */
  shiftThreshold: number;
}

/**
 * Maps item type IDs (e.g. `"minecraft:apple"`) to their aux values (`raw_id * 65536`).
 *
 * Generated by the `item-aux` Regolith filter at `BP/scripts/data/itemAuxMap.generated.json`.
 */
export type ItemAuxMap = Record<string, number>;

/**
 * Context that provides the item aux map (typeId → aux value) to the component tree.
 *
 * Seeded automatically at the render root with calibrated data from the `item-aux`
 * Regolith filter — no provider needed. `ItemRenderer` just works out of the box.
 *
 * To override for a subtree (e.g. custom item data), wrap with this context:
 *
 * ```tsx
 * <ItemAuxContext value={myCustomAuxMap}>
 *   <MyInventory />
 * </ItemAuxContext>
 * ```
 *
 * If the `item-aux` generated package is missing, `ItemRenderer` will throw an
 * `ItemAuxError` at render time.
 */
export const ItemAuxContext = createContext<ItemAuxMap | null>(null);
