import { createContext } from '../core/fabric/context';

/**
 * Maps translation keys (e.g. `"ui.myscreen.title"`) to their resolved display strings.
 *
 * Generated by the `translation-keys` Regolith filter at `BP/scripts/data/translationKeys.generated.json`.
 */
export type TranslationKeysMap = Record<string, string>;

/**
 * Context that provides the translation keys map (key → resolved string) to the component tree.
 *
 * Seeded automatically at the render root with data from the `translation-keys`
 * Regolith filter — no provider needed. `Text` with a `localizationKey` prop just works.
 *
 * To override for a subtree (e.g. a different language or custom strings), wrap with this context:
 *
 * ```tsx
 * <TranslationKeysContext value={myTranslationKeys}>
 *   <MyScreen />
 * </TranslationKeysContext>
 * ```
 *
 * If the `translation-keys` generated package is missing, using `localizationKey` will
 * throw a `TranslationKeysError` at render time.
 */
export const TranslationKeysContext = createContext<TranslationKeysMap | null>(null);
