import { createContext } from '../core/fabric/context';

/**
 * Maps translation keys (e.g. `"ui.myscreen.title"`) to their resolved display strings.
 *
 * Generated by the `translation-keys` Regolith filter at `BP/scripts/data/translationKeys.generated.json`.
 */
export type TranslationKeysMap = Record<string, string>;

/**
 * Context that provides the translation keys map (key → resolved string) to the component tree.
 *
 * Using `Text` with a `localizationKey` prop requires the `translation-keys`
 * Regolith filter and this context at the root of the UI. The filter resolves
 * keys from your pack's .lang files into a generated module that you pass in:
 *
 * ```tsx
 * import translationKeys from '@bedrock-core/generated/translation-keys';
 *
 * <TranslationKeysContext value={translationKeys}>
 *   <MyScreen />
 * </TranslationKeysContext>
 * ```
 *
 * Projects that never use `localizationKey` need neither the filter nor this
 * context. Rendering a `localizationKey` without a provider throws a
 * `TranslationKeysError`.
 *
 * The context can also be nested to override keys for a subtree
 * (e.g. a different language or custom strings).
 */
export const TranslationKeysContext = createContext<TranslationKeysMap | null>(null);
