import type { Player } from '@minecraft/server';
import { createContext } from '../core/fabric/context';

/**
 * Maps translation keys (e.g. `"ui.myscreen.title"`) to their resolved display strings,
 * for ONE locale.
 *
 * Generated by the `translation-keys` Regolith filter at `BP/scripts/data/translationKeys.generated.json`.
 */
export type TranslationKeysMap = Record<string, string>;

/**
 * The generated module's shape: locale code (e.g. `"en_US"`) → {@link TranslationKeysMap}.
 * Bedrock script bundles are static — there's no per-player dynamic import — so every
 * configured locale's map ships in one module; {@link resolveTranslationKeysForPlayer}
 * picks the right one per player at render time.
 */
export type TranslationKeysByLocale = Record<string, TranslationKeysMap>;

/**
 * Pick the {@link TranslationKeysMap} matching a player's client locale
 * (`player.clientSystemInfo.locale`, e.g. `"es_ES"`) out of the generated
 * per-locale module. Falls back to `defaultLocale`, then to any locale present,
 * when the player's own locale wasn't generated (e.g. a language your addon
 * doesn't author content for). Returns `undefined` only when the map is empty —
 * mirrors how a missing key already falls back to rendering the literal key.
 *
 * ```tsx
 * import translationKeys from '@bedrock-core/generated/translation-keys';
 *
 * function App(): JSX.Element {
 *   const player = usePlayer();
 *
 *   return (
 *     <TranslationKeysContext value={resolveTranslationKeysForPlayer(translationKeys, player) ?? null}>
 *       <MyScreen />
 *     </TranslationKeysContext>
 *   );
 * }
 * ```
 */
export function resolveTranslationKeysForPlayer(
  byLocale: TranslationKeysByLocale,
  player: Player,
  defaultLocale = 'en_US',
): TranslationKeysMap | undefined {
  const locale = player.clientSystemInfo.locale;

  return byLocale[locale] ?? byLocale[defaultLocale] ?? Object.values(byLocale)[0];
}

/**
 * Context that provides ONE locale's translation keys map (key → resolved string)
 * to the component tree.
 *
 * Using `Text` with a `localizationKey` prop requires the `translation-keys`
 * Regolith filter and this context at the root of the UI. The filter resolves
 * keys from your pack's .lang files (per configured locale) into a generated
 * module; pick the right locale for the connecting player with
 * {@link resolveTranslationKeysForPlayer} before providing it:
 *
 * ```tsx
 * import translationKeys from '@bedrock-core/generated/translation-keys';
 *
 * const player = usePlayer();
 *
 * <TranslationKeysContext value={resolveTranslationKeysForPlayer(translationKeys, player) ?? null}>
 *   <MyScreen />
 * </TranslationKeysContext>
 * ```
 *
 * Both the filter and this context are OPTIONAL: a `localizationKey` missing
 * from the map (another pack's key, plain text, or no provider at all)
 * measures as the literal key string — mirroring Bedrock, which renders an
 * unmatched key as-is.
 *
 * The context can also be nested to override keys for a subtree
 * (e.g. a different language or custom strings).
 */
export const TranslationKeysContext = createContext<TranslationKeysMap | null>(null);
