/**
 * GENERATED by `scripts/generate-framework-keys.mjs` — do not edit.
 *
 * bedrock-core's own localization keys, mirrored from the resource pack's `.lang` so the layout
 * engine can measure them. See the script for why this is needed and why it is generated.
 *
 * Regenerate with `yarn build` in this package.
 */
export const frameworkGuideKeys: Record<string, string> = {
  "bcg.bedrock_core._adm.note": "§7§lNote",
  "bcg.bedrock_core._adm.tip": "§a§lTip",
  "bcg.bedrock_core._adm.info": "§b§lInfo",
  "bcg.bedrock_core._adm.warning": "§6§lWarning",
  "bcg.bedrock_core._adm.danger": "§c§lDanger",
  "bcg.bedrock_core.commands.nav": "Commands",
  "bcg.bedrock_core.commands.intro": "Every addon built on bedrock-core shares this screen. The list on the left is every addon installed in this world; pick one to reach its settings or its own guide.",
  "bcg.bedrock_core.commands.title": "Commands",
  "bcg.bedrock_core.commands.namespace": "Each addon registers its own commands under its own namespace, written as creator_pack. An addon by \"bt\" called \"gc_graves\" answers to bt_gc_graves. Type a slash and the start of a namespace to see what it offers.",
  "bcg.bedrock_core.commands.cmd_config": "§econfig§r - open that addon's settings: the scope picker if you are an operator, your own settings otherwise",
  "bcg.bedrock_core.commands.cmd_get": "§econfig get <setting>§r - read one of your own settings",
  "bcg.bedrock_core.commands.cmd_set": "§econfig set <setting> <value>§r - change one of your own settings",
  "bcg.bedrock_core.commands.cmd_guide": "§eguide§r - open that addon's guide, a page like this one",
  "bcg.bedrock_core.commands.cmd_list": "§elist§r - open the addon list, the screen behind this one",
  "bcg.bedrock_core.commands.autocomplete": "Settings autocomplete: the chat box offers the ones that addon actually has.",
  "bcg.bedrock_core.commands.h2": "Operators",
  "bcg.bedrock_core.commands.operators": "Anyone can read and change their own settings. Changing what applies to the whole server, to a dimension, or to another player needs operator, and those commands are hidden from everyone else.",
  "bcg.bedrock_core.commands.cmd_getat": "§econfigat get <scope.setting> [target]§r",
  "bcg.bedrock_core.commands.cmd_setat": "§econfigat set <scope.setting> <value> [target]§r",
  "bcg.bedrock_core.commands.scoped": "The scope is part of the setting - server.pricing.tax_rate, player.allow_gifts. For a dimension or player setting, [target] names which one; leave it out to mean yourself, or the dimension you are standing in.",
  "bcg.bedrock_core.commands.tip": "Command blocks can run configat, so server settings can be driven by redstone or a datapack-style setup.",
};
