// Auto-generated by translation-keys Regolith filter. Do not edit by hand.
declare module '*/translationKeys.generated.json' {
  /** Locale code (e.g. "en_US") → key → resolved display string. */
  const value: Record<string, Record<string, string>>;

  export default value;
}

declare module '@bedrock-core/generated/translation-keys' {
  /** Locale code (e.g. "en_US") → key → resolved display string. */
  const value: Record<string, Record<string, string>>;

  export default value;
}
