// Auto-generated by translation-keys Regolith filter. Do not edit by hand.
declare module '*/translationKeys.generated.json' {
  const value: Record<string, string>;

  export default value;
}

declare module '@bedrock-core/generated/translation-keys' {
  const value: Record<string, string>;

  export default value;
}
