// Auto-generated by the guides Regolith filter. Do not edit by hand.
//
// Structural copy of the guide IR types — kept dependency-free so the filter
// works without @bedrock-core/guides installed. The runtime package accepts
// this manifest structurally (its canonical types live in
// @bedrock-core/guides `src/types.ts`).

declare module '@bedrock-core/generated/guides' {
  /** Generated localization key, e.g. 'bcg.my_addon.getting_started.intro.b3'. */
  export type LangKey = string;
  /** Extension-less POSIX path of a page, e.g. 'getting-started/intro'. */
  export type PageId = string;

  export type AdmonitionKind = 'note' | 'tip' | 'info' | 'warning' | 'danger';

  /**
   * One run of a paragraph/list-item's inline content, in document order.
   * A run with `to` is an internal link rendered as its own pressable
   * element woven inline with the surrounding text.
   */
  export interface GuideRun {
    k: LangKey;
    to?: PageId;
  }

  export interface GuideListItem {
    runs: GuideRun[];
    items?: GuideListItem[];
  }

  export type GuideBlock =
    | { t: 'h'; l: 1 | 2 | 3; k: LangKey }
    | { t: 'p'; runs: GuideRun[] }
    | { t: 'ul'; items: GuideListItem[] }
    | { t: 'ol'; items: GuideListItem[]; start?: number }
    | { t: 'img'; src: string; alt?: string; w?: number; h?: number }
    | { t: 'adm'; kind: AdmonitionKind; titleK?: LangKey; blocks: GuideBlock[] }
    | { t: 'code'; lang?: string; lines: string[] }
    | { t: 'hr' }
    | { t: 'cmp'; name: string; props?: Record<string, unknown>; blocks?: GuideBlock[] };

  export type GuideTreeNode =
    | { t: 'page'; id: PageId; titleK: LangKey }
    | { t: 'cat'; id: string; labelK: LangKey; collapsed?: boolean; link?: PageId; children: GuideTreeNode[] };

  export interface GuidePage {
    id: PageId;
    titleK: LangKey;
    blocks: GuideBlock[];
    prev?: PageId;
    next?: PageId;
  }

  export interface GuideManifest {
    /** IR format version. */
    v: 1;
    /** Addon namespace (the filter's keyPrefix, sanitized). */
    ns: string;
    defaultLocale: string;
    locales: string[];
    tree: GuideTreeNode[];
    pages: Record<PageId, GuidePage>;
  }

  const manifest: GuideManifest;
  export default manifest;
}

declare module '*/guides.generated.json' {
  const manifest: import('@bedrock-core/generated/guides').GuideManifest;
  export default manifest;
}
