// Auto-generated by item-aux Regolith filter. Do not edit by hand.
declare module '*/itemAuxMap.generated.json' {
  interface ItemAuxData {
    /** typeId → aux value for every vanilla, custom, and block item. */
    items: Record<string, number>;
    /**
     * Lowest aux value belonging to a vanilla item that may be displaced
     * by developer-build items absent from the public API.
     * = (shiftThreshold + customItemCount) * 65536
     */
    correctionBoundaryAux: number;
  }
  const value: ItemAuxData;

  export default value;
}

declare module '@bedrock-core/generated/item-aux' {
  interface ItemAuxData {
    items: Record<string, number>;
    correctionBoundaryAux: number;
  }
  const value: ItemAuxData;

  export default value;
}
