// Auto-generated by item-aux Regolith filter. Do not edit by hand.
declare module '*/itemAuxMap.generated.json' {
  interface ItemAuxData {
    /** Raw numeric IDs for all vanilla items/blocks (typeId → raw_id). */
    vanillaRawIds: Record<string, number>;
    /** Offset added to |minVanillaRawId| to compute the custom block base ID. */
    blockBaseOffset: number;
    /** First vanilla raw_id that may be displaced by developer-build items absent from the public API. */
    shiftThreshold: number;
  }
  const value: ItemAuxData;

  export default value;
}

declare module '@bedrock-core/generated/item-aux' {
  interface ItemAuxData {
    vanillaRawIds: Record<string, number>;
    blockBaseOffset: number;
    shiftThreshold: number;
  }
  const value: ItemAuxData;

  export default value;
}
