// The framework's screens, reduced to references.
//
// The framework has no realm: nothing calls `core.register()` for it, so the
// screens it owns — its guide and its page in the addon list — cannot be
// published the way an addon publishes its own. They are baked into this
// pack instead, and what presenting them needs (each screen's title, the
// values its entries are shown with, where every press leads) is emitted
// here as data that `@bedrock-core/config` ships, so every realm shows them
// from the render pack the client already has, none of this pack's script
// involved.
//
// Runs after ui-compile, which wrote the registration module this reads, and
// before the bundler. The references are built by the same library the
// screens were compiled against, in the same way an addon builds its own at
// startup; the result is written into the config package's source, where it
// is committed like any generated resource.

import fs from 'node:fs';
import path from 'node:path';

import { evaluateEntry } from '../../../../regolith-filters/ui-compile/lib/load';

const projectRoot = process.env['ROOT_DIR'];

if (!projectRoot) {
  console.error('❌ references: ROOT_DIR environment variable not set — this filter must be run by Regolith');
  process.exit(1);
}

/** The namespace this pack's screens are compiled under; the page's marker names it. */
const NAMESPACE = 'core';
const REGISTRATION = 'data/ui/ui.generated.ts';
const I18N_BUNDLE = 'data/i18n/i18n.generated.json';
const GUIDES_BUNDLE = 'data/guides/guides.generated.json';
const PAGE = 'BP/scripts/screens/framework.screen.tsx';
const OUTPUT = path.resolve(projectRoot, '..', 'config', 'src', 'generated', 'framework.generated.ts');

for (const required of [REGISTRATION, I18N_BUNDLE, PAGE]) {
  if (!fs.existsSync(required)) {
    console.error(`❌ references: ${required} is missing — the filters before this one did not write it`);
    process.exit(1);
  }
}

interface References {
  guide: unknown;
  page: { v: 1; values: string[]; targets: (string | null)[] };
}

// Everything in one bundle, so the screens the registration module registers
// are the ones the references are read from.
const entry = `
import i18nBundle from ${JSON.stringify(path.resolve(I18N_BUNDLE))};
import { createI18n } from '@bedrock-core/i18n';

createI18n(i18nBundle);

import ${JSON.stringify(path.resolve(REGISTRATION))};
import { guideReference } from '@bedrock-core/guides';
import { addonPageReference } from '@bedrock-core/config/compiled';
import Page from ${JSON.stringify(path.resolve(PAGE))};

export default {
  guide: guideReference(${JSON.stringify(NAMESPACE)}),
  page: addonPageReference(Page),
};
`;

const references = await evaluateEntry<References>({
  contents: entry,
  resolveDir: process.cwd(),
  sourcefile: 'references.entry.ts',
  loader: 'ts',
  cacheDir: path.join(projectRoot, '.regolith', 'cache', 'references'),
  aliases: Object.fromEntries(
    [['@bedrock-core/generated/i18n', I18N_BUNDLE], ['@bedrock-core/generated/guides', GUIDES_BUNDLE]]
      .filter(([, file]) => fs.existsSync(file as string))
      .map(([specifier, file]) => [specifier, path.resolve(file as string)]),
  ),
  key: 'references',
}).catch((error: unknown) => {
  console.error(`❌ references: ${String(error instanceof Error ? error.message : error)}`);

  return process.exit(1);
});

if (references.guide === undefined) {
  console.error(`❌ references: no compiled guide "${NAMESPACE}" was registered — did the guides filter run?`);
  process.exit(1);
}

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
fs.writeFileSync(
  OUTPUT,
  [
    '// GENERATED by the render pack\'s references filter — do not edit.',
    '//',
    '// The framework\'s own screens, baked into the render pack, as what',
    '// presenting them needs: a title per screen, the values its entries are',
    '// shown with, and where each press leads. Nothing registers the framework,',
    '// so no realm can publish these the way an addon publishes its page and',
    '// guide; every realm carries them here instead and shows them from the',
    '// pack the client already has.',
    '',
    'import type { GuideReference } from \'@bedrock-core/guides\';',
    'import type { AddonPageReference } from \'../compiled/page.screen\';',
    '',
    '/** The namespace the framework\'s screens are compiled under: what its page\'s marker names. */',
    `export const FRAMEWORK_NAMESPACE = ${JSON.stringify(NAMESPACE)};`,
    '',
    `export const FRAMEWORK_GUIDE: GuideReference = ${JSON.stringify(references.guide, null, 2)};`,
    '',
    `export const FRAMEWORK_PAGE: AddonPageReference = ${JSON.stringify(references.page, null, 2)};`,
    '',
  ].join('\n'),
  'utf-8',
);

console.log(`✅ references: framework guide and page → ${path.relative(projectRoot, OUTPUT).split(path.sep).join('/')}`);
